### PR TITLE
curvefs/client: fix read lru bug

### LINKED ISSUE #684: curvefs:  read lru cache coredump
**Describe the bug (描述bug)**

curve-fuse core dump when testing

image

**To Reproduce (复现方法)**

vdbench profile
```bash
fsd=fsd1,anchor=/mnt/vdbench3,depth=1,width=10,files=10,sizes=(100m,0),shared=yes,openflags=o_direct
fwd=fwd1,fsd=fsd1,threads=10,xfersize=(512,20,4k,20,64k,20,512k,20,1024k,20),fileio=random,fileselect=random,rdpct=50
rd=rd1,fwd=fwd*,fwdrate=max,format=restart,elapsed=7200,interval=1
```

**Expected behavior (期望行为)**

**Versions (各种版本)**
OS: debian buster
Compiler: gcc (Debian 8.3.0-6) 8.3.0
fs: 087c8a3dd8c983ce3e7cb2fa6ac301af4a20fe3f

**Additional context/screenshots (更多上下文/截图)**

image

### PR DESCRIPTION
**Pull request by wu-hanqing**
### What problem does this PR solve?

Issue Number: close #684 

Problem Summary:

### What is changed and how it works?

What's Changed:

How it Works:

Side effects(Breaking backward compatibility? Performance regression?): 

### Check List

- [x] Relevant documentation/comments is changed or added
- [x] I acknowledge that all my contributions will be made under the project's license

### CODE REVIEW

File: curvefs/src/client/s3/client_s3_cache_manager.cpp [hunk 1]
```diff
@@ -67,44 +67,64 @@ void FsCacheManager::ReleaseFileCacheManager(uint64_t inodeId) {
...
-        lruByte_ -= trimDataCache->GetLen();
-        trimDataCache->Release();
-        lruReadDataCacheList_.pop_back();
+    if (lruByte_ >= readCacheMaxByte_) {
+        uint64_t retiredBytes = 0;
+        auto iter = lruReadDataCacheList_.end();
+
+        while (lruByte_ >= readCacheMaxByte_) {
+            --iter;
+            auto& trim = *iter;
```
Comment (ilixiaocui) [inline curvefs/src/client/s3/client_s3_cache_manager.cpp:84]: Why not use iter directly？

File: curvefs/src/client/s3/client_s3_cache_manager.cpp [hunk 2]
```diff
@@ -67,44 +67,64 @@ void FsCacheManager::ReleaseFileCacheManager(uint64_t inodeId) {
...
     // trim cache without consider dataCache's size, because its size is
     // expected to be very smaller than `readCacheMaxByte_`
-    while (lruByte_ >= readCacheMaxByte_) {
-        auto& trimDataCache = lruReadDataCacheList_.back();
-        VLOG(3) << "lru release data cache, size: "
-        << trimDataCache->GetLen();
-        lruByte_ -= trimDataCache->GetLen();
-        trimDataCache->Release();
-        lruReadDataCacheList_.pop_back();
+    if (lruByte_ >= readCacheMaxByte_) {
```
Comment (ilixiaocui) [inline curvefs/src/client/s3/client_s3_cache_manager.cpp:78]: if is redundant？
{
      uint64_t retiredBytes = 0;
      auto iter = lruReadDataCacheList_.end();
      while(){}
}

File: curvefs/src/client/s3/client_s3_cache_manager.cpp [hunk 3]
```diff
@@ -1584,5 +1588,51 @@ void DataCache::UpdateInodeChunkInfo(S3ChunkInfoList *s3ChunkInfoList,
...
+}
+
+void FsCacheManager::ReadCacheReleaseExecutor::Stop() {
+    std::lock_guard<std::mutex> lk(mtx_);
+    running_ = false;
+    cond_.notify_one();
+}
+
+FsCacheManager::ReadCacheReleaseExecutor::~ReadCacheReleaseExecutor() {
+    Stop();
```
Comment (ilixiaocui) [inline curvefs/src/client/s3/client_s3_cache_manager.cpp:1626]: print log

File: curvefs/src/client/s3/client_s3_cache_manager.cpp [hunk 4]
```diff
@@ -1405,9 +1408,10 @@ void DataCache::Write(uint64_t chunkPos, uint64_t len, const char *data,
 }
 
 void DataCache::Release() {
-    chunkCacheManager_->ReleaseReadDataCache(chunkPos_);
-
-    return;
+    auto chunkCacheManager = chunkCacheManager_.lock();
```
Comment (ilixiaocui) [inline curvefs/src/client/s3/client_s3_cache_manager.cpp:1411]: do not need. 
Release()  is now only called by ReadCacheReleaseExecutor. We can get chunkCacheManager in FsCacheManager.
Datacahe does not require reverse dependency on chunkCacheManager.

File: curvefs/src/client/s3/client_s3_cache_manager.h [hunk 5]
```diff
@@ -91,25 +91,32 @@ struct ObjectChunkInfo {
...
+          inReadCache_(false) {
         data_ = new char[len];
         memcpy(data_, data, len);
         createTime_ = ::curve::common::TimeUtility::GetTimeofDaySec();
-        //  dirty_.exchange(true, std::memory_order_acq_rel);
     }
     DataCache(S3ClientAdaptorImpl *s3ClientAdaptor,
-              ChunkCacheManager *chunkCacheManager, uint64_t chunkPos,
-              uint64_t len)
+              const std::shared_ptr<ChunkCacheManager>& chunkCacheManager,
```
Comment (baijiaruo) [inline curvefs/src/client/s3/client_s3_cache_manager.h:109]: & is near chunkCacheManager，The format needs to be uniform

File: curvefs/src/client/s3/client_s3_cache_manager.cpp [hunk 6]
```diff
@@ -1166,43 +1175,38 @@ void ChunkCacheManager::AddReadDataCache(DataCachePtr dataCache) {
...
         auto iter = dataRCacheMap_.find(key);
-        std::list<DataCachePtr>::iterator dcpIter = iter->second.first;
+        std::list<DataCachePtr>::iterator dcpIter = iter->second;
         s3ClientAdaptor_->GetFsCacheManager()->Delete(dcpIter);
         dataRCacheMap_.erase(iter);
     }
 
-    dataRCacheMap_.emplace(
-        chunkPos, s3ClientAdaptor_->GetFsCacheManager()->Set(dataCache));
+    std::list<DataCachePtr>::iterator newIter =
```
Comment (baijiaruo) [inline curvefs/src/client/s3/client_s3_cache_manager.cpp:1203]: Don't see the difference

File: curvefs/src/client/s3/client_s3_cache_manager.cpp (hunk 1 above)
Comment (wu-hanqing) [reply curvefs/src/client/s3/client_s3_cache_manager.cpp:84]: it's more readable and concise than
```cpp
(*iter)->SetReadCacheState(false);
lruByte_ -= (*iter)->GetLen();
retiredBytes += (*iter)->GetLen();
```

File: curvefs/src/client/s3/client_s3_cache_manager.cpp (hunk 2 above)
Comment (wu-hanqing) [reply curvefs/src/client/s3/client_s3_cache_manager.cpp:78]: not really, if do what you say, another if should be added to check whether I have to cut some data chches from lruReadDataCacheList_ or not, because while loop does not pop any data cache.

File: curvefs/src/client/s3/client_s3_cache_manager.cpp (hunk 3 above)
Comment (wu-hanqing) [reply curvefs/src/client/s3/client_s3_cache_manager.cpp:1616]: fix

File: curvefs/src/client/s3/client_s3_cache_manager.cpp (hunk 4 above)
Comment (wu-hanqing) [reply curvefs/src/client/s3/client_s3_cache_manager.cpp]: this change has been removed because the case that can cause chunkCacheManager_ expired has been implicitly fix by @baijiaruo

File: curvefs/src/client/s3/client_s3_cache_manager.h (hunk 5 above)
Comment (wu-hanqing) [reply curvefs/src/client/s3/client_s3_cache_manager.h]: fix

File: curvefs/src/client/s3/client_s3_cache_manager.cpp (hunk 6 above)
Comment (wu-hanqing) [reply curvefs/src/client/s3/client_s3_cache_manager.cpp]: fix

**Review by ilixiaocui — APPROVED** [review]

**Review by baijiaruo — APPROVED** [review]
