### PR TITLE
curvefs/client: fix bug that abort uplaod when read one file failed

### LINKED ISSUE #877: Umount fs write cache data is launched before uploading
**Describe the bug (描述bug)**
Umount fs write cache data is launched before uploading

**To Reproduce (复现方法)**
1、fio 4k randwrite fuse
2、curveadm umount fs
3、
image

**Expected behavior (期望行为)**

**Versions (各种版本)**
OS:
Compiler:
curve-mds:
curve-chunkserver:
curve-snapshotcloneserver:
curve-sdk:
nebd:
curve-nbd:

**Additional context/screenshots (更多上下文/截图)**

### PR DESCRIPTION
**Pull request by wuhongsong**
when read one file from disk write cache failed, continue to upload
other files

### What problem does this PR solve?

Issue Number: close #877

### CODE REVIEW

**Comment by YunhuiChen** [comment]
recheck

**Comment by YunhuiChen** [comment]
recheck

**Comment by YunhuiChen** [comment]
recheck

**Comment by YunhuiChen** [comment]
recheck

**Comment by wuhongsong** [comment]
recheck

**Comment by YunhuiChen** [comment]
recheck

**Comment by YunhuiChen** [comment]
recheck

File: curvefs/src/client/s3/disk_cache_write.cpp [hunk 1]
```diff
@@ -243,8 +243,9 @@ int DiskCacheWrite::UploadAllCacheWriteFile() {
         if (doRet < 0 || buffer == nullptr) {
             if (buffer != nullptr)
                 posixWrapper_->free(buffer);
-            LOG(ERROR) << "read file is failed";
-            return -1;
+            LOG(WARNING) << "read file is failed";
```
Comment (aspirer) [inline curvefs/src/client/s3/disk_cache_write.cpp:246]: it is better to log the read failed filename.

**Comment by wuhongsong** [comment]
recheck

**Review by xu-chaojie — APPROVED** [review]

**Review by baijiaruo — APPROVED** [review]
