### PR TITLE
curvefs/metaserver: fixed the length of the saved string exceeds the limit size.

### LINKED ISSUE #768: Metaserver copySet Failed to create a snapshot
**Describe the bug (描述bug)**
Metaserver copySet Failed to create a snapshot

**To Reproduce (复现方法)**

image

**Expected behavior (期望行为)**

**Versions (各种版本)**
OS:
Compiler:
curve-mds:
curve-chunkserver:
curve-snapshotcloneserver:
curve-sdk:
nebd:
curve-nbd:

**Additional context/screenshots (更多上下文/截图)**

### PR DESCRIPTION
**Pull request by Wine93**
### What problem does this PR solve?

Issue Number: close #768

Problem Summary: The length of the saved string exceeds the limit

### What is changed and how it works?

What's Changed:

How it Works:

Side effects(Breaking backward compatibility? Performance regression?): 

### Check List

- [ ] Relevant documentation/comments is changed or added
- [ ] I acknowledge that all my contributions will be made under the project's license

### CODE REVIEW

File: curvefs/src/metaserver/dumpfile.cpp [hunk 1]
```diff
@@ -247,6 +243,8 @@ DUMPFILE_ERROR DumpFile::LoadString(std::string* str,
                                     size_t length,
                                     uint32_t* checkSum) {
     if (length > kMaxStringLength_) {
+        LOG(ERROR) << "The loaded string is too large, size("
```
Comment (wu-hanqing) [inline curvefs/src/metaserver/dumpfile.cpp:246]: if you don't constrain size when saving, why add constraints on loading?

File: curvefs/src/metaserver/dumpfile.cpp [hunk 2]
```diff
@@ -203,10 +203,6 @@ DUMPFILE_ERROR DumpFile::SaveString(const std::string& str,
                                     off_t* offset,
                                     uint32_t* checkSum) {
     size_t length = str.size();
-    if (length > kMaxStringLength_) {
-        return DUMPFILE_ERROR::EXCEED_MAX_STRING_LENGTH;
```
Comment (cw123) [inline curvefs/src/metaserver/dumpfile.cpp:207]: why delelte?

File: curvefs/src/metaserver/dumpfile.cpp [hunk 3]
```diff
@@ -65,7 +65,7 @@ using ::curve::common::CRC32;
 
 const std::string DumpFile::kCurvefs_ = "CURVEFS";  // NOLINT
 const uint8_t DumpFile::kVersion_ = 1;
-const uint32_t DumpFile::kMaxStringLength_ = 1024 * 1024;  // 1MB
+const uint32_t DumpFile::kMaxStringLength_ = 1024 * 1024 * 1024;  // 1GB
```
Comment (cw123) [inline curvefs/src/metaserver/dumpfile.cpp:68]: 1GB is too large

**Review by wu-hanqing — APPROVED** [review]

**Review by cw123 — APPROVED** [review]
