### PR TITLE
curvefs/client: perf optimize

### LINKED ISSUE #996: When the disk cache is sufficient, the sequential write performance is basically 128MB/s and 64MB/s
**Describe the bug (描述bug)**

image
image

**To Reproduce (复现方法)**
fsd=fsd3,anchor=/home/nbs/failover/test5,depth=1,width=10,files=10,sizes=1000m,shared=yes,openflags=o_direct
fwd=fwd1,fsd=fsd*,threads=10,xfersize=(512k,50,1024k,50),fileio=random,fileselect=random,rdpct=0
rd=rd1,fwd=fwd*,fwdrate=max,format=restart,elapsed=1400,interval=1

**Expected behavior (期望行为)**

**Versions (各种版本)**
OS:
Compiler:
curve-mds:
curve-chunkserver:
curve-snapshotcloneserver:
curve-sdk:
nebd:
curve-nbd:

**Additional context/screenshots (更多上下文/截图)**

### LINKED ISSUE #1235: vdbench io frequently drops 0, up to a few minutes
**Describe the bug (描述bug)**

image

**To Reproduce (复现方法)**
data_errors=1
fsd=fsd1,anchor=/home/nbs/failover/test1,depth=1,width=10,files=10,sizes=1000m,shared=yes,openflags=o_direct
fsd=fsd2,anchor=/home/nbs/failover/test2,depth=1,width=10,files=10,sizes=(200m,0),shared=yes,openflags=o_direct
fsd=fsd3,anchor=/home/nbs/failover/test3,depth=1,width=10,files=100,sizes=(1m,0),shared=yes,openflags=o_direct
fsd=fsd4,anchor=/home/nbs/failover/test4,depth=1,width=10,files=10,sizes=(1000m,0),shared=yes,openflags=o_direct
fsd=fsd5,anchor=/home/nbs/failover/test5,depth=1,width=10,files=10,sizes=(100m,0),shared=yes,openflags=o_direct
fsd=fsd6,anchor=/home/nbs/failover/test6,depth=1,width=10,files=10,sizes=(100m,0),shared=yes,openflags=o_direct
fsd=fsd7,anchor=/home/nbs/failover/test7,depth=1,width=10,files=10,sizes=(10m,0),shared=yes,openflags=o_direct
fwd=fwd1,fsd=fsd*,threads=10,xfersize=(512,20,4k,20,64k,20,512k,20,1024k,20),fileio=random,fileselect=random,rdpct=50
rd=rd1,fwd=fwd*,fwdrate=max,format=restart,elapsed=120000,interval=1

**Expected behavior (期望行为)**

**Versions (各种版本)**
OS:
Compiler:
curve-mds:
curve-chunkserver:
curve-snapshotcloneserver:
curve-sdk:
nebd:
curve-nbd:

**Additional context/screenshots (更多上下文/截图)**

### LINKED ISSUE #1251: After a long vdbench test, the performance is in the single digits
**Describe the bug (描述bug)**

image

**To Reproduce (复现方法)**
data_errors=1
fsd=fsd1,anchor=/home/nbs/failover/test9,depth=1,width=10,files=10,sizes=1000m,shared=yes,openflags=o_direct
fsd=fsd2,anchor=/home/nbs/failover/test2,depth=1,width=10,files=10,sizes=(200m,0),shared=yes,openflags=o_direct
fsd=fsd3,anchor=/home/nbs/failover/test3,depth=1,width=10,files=100,sizes=(1m,0),shared=yes,openflags=o_direct
fsd=fsd4,anchor=/home/nbs/failover/test4,depth=1,width=10,files=10,sizes=(1000m,0),shared=yes,openflags=o_direct
fsd=fsd5,anchor=/home/nbs/failover/test5,depth=1,width=10,files=10,sizes=(100m,0),shared=yes,openflags=o_direct
fsd=fsd6,anchor=/home/nbs/failover/test6,depth=1,width=10,files=10,sizes=(100m,0),shared=yes,openflags=o_direct
fsd=fsd7,anchor=/home/nbs/failover/test7,depth=1,width=10,files=10,sizes=(10m,0),shared=yes,openflags=o_direct
fwd=fwd1,fsd=fsd*,threads=10,xfersize=(512,20,4k,20,64k,20,512k,20,1024k,20),fileio=random,fileselect=random,rdpct=50
rd=rd1,fwd=fwd*,fwdrate=max,format=restart,elapsed=120000,interval=1

**Expected behavior (期望行为)**

**Versions (各种版本)**
OS:
Compiler:
curve-mds:
curve-chunkserver:
curve-snapshotcloneserver:
curve-sdk:
nebd:
curve-nbd:

**Additional context/screenshots (更多上下文/截图)**

### PR DESCRIPTION
**Pull request by wuhongsong**
### What problem does this PR solve?

Issue Number: close #996  
Issue Number: close #1235   
Issue Number: close #1251

### CODE REVIEW

**Comment by wuhongsong** [comment]
recheck

**Comment by wuhongsong** [comment]
recheck

**Comment by wuhongsong** [comment]
recheck

**Comment by wuhongsong** [comment]
recheck

**Comment by wuhongsong** [comment]
recheck

**Comment by wuhongsong** [comment]
recheck

**Comment by wuhongsong** [comment]
recheck

File: WORKSPACE [hunk 1]
```diff
@@ -34,7 +34,7 @@ bazel_skylib_workspace()
 
 git_repository(
     name = "com_github_baidu_braft",
-    remote = "https://github.com/baidu/braft",
+    remote = "https://gitee.com/baidu/braft",
```
Comment (xu-chaojie) [inline WORKSPACE:37]: ???

File: curvefs/src/client/s3/client_s3_adaptor.cpp [hunk 2]
```diff
@@ -369,5 +377,25 @@ int S3ClientAdaptorImpl::ClearDiskCache(int64_t inodeId) {
...
+    auto task = [this, context]() {
+        this->FlushChunkClosure(context);
+    };
+    taskPool_.Enqueue(task);
+}
+
+int S3ClientAdaptorImpl::FlushChunkClosure(
+  std::shared_ptr<FlushChunkCacheContext> context) {
+    VLOG(9) << "FlushChunkCacheClosure start: " << context->inode;
+    FlushChunkCacheClosure done(context);
```
Comment (xu-chaojie) [inline curvefs/src/client/s3/client_s3_adaptor.cpp:391]: If FlushChunkCacheClosure is only used here, so there is no need to package such a class, just call ctx->cb(ctx)  directly

File: curvefs/src/client/s3/client_s3_adaptor.h [hunk 3]
```diff
@@ -89,6 +93,17 @@ class S3ClientAdaptor {
                                 uint64_t start) = 0;
 };
 
+using FlushChunkCacheCallBack = std::function<
+  void(const std::shared_ptr<FlushChunkCacheContext>&)>;
+
+struct FlushChunkCacheContext {
+    uint64_t inode;
+    ChunkCacheManagerPtr ptr;
```
Comment (xu-chaojie) [inline curvefs/src/client/s3/client_s3_adaptor.h:101]: Use meaningful variable names, don't just use ’ptr‘

File: curvefs/src/client/s3/client_s3_cache_manager.cpp [hunk 4]
```diff
@@ -932,45 +932,78 @@ void FileCacheManager::TruncateCache(uint64_t offset, uint64_t fileSize) {
...
-        {
-            WriteLockGuard writeLockGuard(rwLock_);
-            auto iter1 = chunkCacheMap_.find(iter->first);
-            if (iter1 == chunkCacheMap_.end()) {
-                VLOG(1) << "Flush, chunk cache for inodeid: " << inode_
+    std::atomic<uint64_t> pendingReq(0);
+    curve::common::CountDownEvent cond(1);
+    FlushChunkCacheCallBack cb =
+        [&](const std::shared_ptr<FlushChunkCacheContext> &context) {
+            ret = context->retCode;
```
Comment (xu-chaojie) [inline curvefs/src/client/s3/client_s3_cache_manager.cpp:946]: Is it possible that the failed return value here will be overwritten by a later correct return value?

Comment (xu-chaojie) [inline curvefs/src/client/s3/client_s3_cache_manager.cpp:946]: The context is shared by multiple threads, is there no need to lock here?

File: curvefs/src/client/s3/client_s3_adaptor.cpp [hunk 5]
```diff
@@ -369,5 +377,25 @@ int S3ClientAdaptorImpl::ClearDiskCache(int64_t inodeId) {
...
+    brpc::ClosureGuard done_guard(&done);
+    CURVEFS_ERROR ret = context->ptr->Flush(context->inode, context->force);
+    // 设置返回值
+    done.ctx->retCode = ret;
```
Comment (xu-chaojie) [inline curvefs/src/client/s3/client_s3_adaptor.cpp:395]: Is there no need to lock ctx here?

File: curvefs/src/client/s3/client_s3_cache_manager.cpp [hunk 6]
```diff
@@ -2031,20 +2064,20 @@ CURVEFS_ERROR DataCache::Flush(uint64_t inodeId, bool force, bool toS3) {
         PutObjectAsyncCallBack cb =
             [&](const std::shared_ptr<PutObjectAsyncContext> &context) {
                 if (context->retCode == 0) {
+                    if (pendingReq.fetch_sub(
```
Comment (xu-chaojie) [inline curvefs/src/client/s3/client_s3_cache_manager.cpp:2067]: Don't move the if sentence to the front，it will cause core dumped because s3Metric_ will be destructed before being accessed, see pr : https://github.com/opencurve/curve/pull/1184

Comment (xu-chaojie) [reply curvefs/src/client/s3/client_s3_cache_manager.cpp:2067]: By the way, adding a comment here in case someone else changes it

File: curvefs/src/client/s3/disk_cache_manager.cpp [hunk 7]
```diff
@@ -84,27 +85,31 @@ int DiskCacheManager::Init(S3Client *client,
...
     }
-    // start aync upload thread
-    cacheWrite_->AsyncUploadRun();
-    std::thread uploadThread =
-        std::thread(&DiskCacheManager::UploadAllCacheWriteFile, this);
-    uploadThread.detach();
-
-    // load all cache read file
+    /*
+       把所有cacheread上的文件都load上来，如果cachewrite里没有该文件，那么bool设置为false。
```
Comment (xu-chaojie) [inline curvefs/src/client/s3/disk_cache_manager.cpp:97]: Use English comments

File: curvefs/src/client/s3/disk_cache_manager_impl.cpp [hunk 8]
```diff
@@ -48,10 +48,31 @@ int DiskCacheManagerImpl::Init(const S3ClientAdaptorOption option) {
...
+    auto task = [this, context]() {
+        this->WriteClosure(context);
+    };
+    taskPool_.Enqueue(task);
+}
+
+int DiskCacheManagerImpl::WriteClosure(
+  std::shared_ptr<PutObjectAsyncContext> context) {
+    VLOG(9) << "WriteClosure start, name: " << context->key;
+    WriteDiskCacheClosure done(context);
```
Comment (xu-chaojie) [inline curvefs/src/client/s3/disk_cache_manager_impl.cpp:68]: Closure is meaningless, it is better to call directly

File: src/common/lru_cache.h [hunk 9]
```diff
@@ -279,6 +302,24 @@ bool LRUCache<K, V, KeyTraits, ValueTraits>::Get(const K &key, V *value) {
     return true;
 }
 
+template <typename K,  typename V, typename KeyTraits, typename ValueTraits>
+bool LRUCache<K, V, KeyTraits, ValueTraits>::GetFirst(const V value, K *key) {
+    ::curve::common::WriteLockGuard guard(lock_);
+    if (ll_.empty()) {
+        return false;
+    }
+    auto it = ll_.rbegin();
```
Comment (xu-chaojie) [inline src/common/lru_cache.h:311]: Since you use rbegin to traverse from the back, should this function be called GetLast

Comment (wuhongsong) [reply src/common/lru_cache.h:311]: fix

File: curvefs/src/client/s3/disk_cache_manager.cpp (hunk 7 above)
Comment (wuhongsong) [reply curvefs/src/client/s3/disk_cache_manager.cpp:97]: fix

File: curvefs/src/client/s3/client_s3_adaptor.cpp (hunk 2 above)
Comment (wuhongsong) [reply curvefs/src/client/s3/client_s3_adaptor.cpp:391]: fix

File: src/common/lru_cache.h [hunk 10]
```diff
@@ -279,6 +302,24 @@ bool LRUCache<K, V, KeyTraits, ValueTraits>::Get(const K &key, V *value) {
     return true;
 }
 
+template <typename K,  typename V, typename KeyTraits, typename ValueTraits>
+bool LRUCache<K, V, KeyTraits, ValueTraits>::GetFirst(const V value, K *key) {
```
Comment (baijiaruo) [inline src/common/lru_cache.h:306]: Why does lru provide these operations

File: curvefs/src/client/s3/disk_cache_manager.cpp [hunk 11]
```diff
@@ -324,40 +335,32 @@ bool DiskCacheManager::IsDiskCacheSafe() {
...
-            std::string cacheKey, cacheKeyBfo, cacheKeyDel;
-            if (!cachedObjName_->GetBack(&cacheKey)) {
-                VLOG(3) << "remove disk file error"
-                        << ", cachedObjName is empty.";
-                continue;
-            }
             while (!IsDiskCacheSafe()) {
-                cacheKeyDel = cacheKey;
-                if (!cachedObjName_->GetBefore(cacheKey, &cacheKeyBfo)) {
+                if (!cachedObjName_->GetFirst(false, &cacheKey)) {
```
Comment (baijiaruo) [inline curvefs/src/client/s3/disk_cache_manager.cpp:356]: I don't think lru should do this

File: curvefs/src/client/s3/client_s3_adaptor.h (hunk 3 above)
Comment (wuhongsong) [reply curvefs/src/client/s3/client_s3_adaptor.h:101]: fix

File: src/common/lru_cache.h (hunk 9 above)
Comment (wuhongsong) [reply src/common/lru_cache.h:311]: fix

File: curvefs/src/client/s3/client_s3_adaptor.cpp [hunk 12]
```diff
@@ -369,5 +377,25 @@ int S3ClientAdaptorImpl::ClearDiskCache(int64_t inodeId) {
...
+        this->FlushChunkClosure(context);
+    };
+    taskPool_.Enqueue(task);
+}
+
+int S3ClientAdaptorImpl::FlushChunkClosure(
+  std::shared_ptr<FlushChunkCacheContext> context) {
+    VLOG(9) << "FlushChunkCacheClosure start: " << context->inode;
+    FlushChunkCacheClosure done(context);
+    brpc::ClosureGuard done_guard(&done);
```
[the remark this answers is not in the document]
Comment (wuhongsong) [reply curvefs/src/client/s3/client_s3_adaptor.cpp:392]: has deleted

File: curvefs/src/client/s3/client_s3_adaptor.cpp [hunk 13]
```diff
@@ -369,5 +377,25 @@ int S3ClientAdaptorImpl::ClearDiskCache(int64_t inodeId) {
...
+    CURVEFS_ERROR ret = context->ptr->Flush(context->inode, context->force);
```
[the remark this answers is not in the document]
Comment (wuhongsong) [reply curvefs/src/client/s3/client_s3_adaptor.cpp:393]: fix

File: curvefs/src/client/s3/client_s3_cache_manager.cpp [hunk 14]
```diff
@@ -1434,7 +1467,7 @@ CURVEFS_ERROR ChunkCacheManager::Flush(uint64_t inodeId, bool force,
             }
         }
     }
-
+    VLOG(6) << "ChunkCacheManager flush end ";
```
[the remark this answers is not in the document]
Comment (wuhongsong) [reply curvefs/src/client/s3/client_s3_cache_manager.cpp:1470]: fix

File: curvefs/src/client/s3/disk_cache_manager.cpp (hunk 11 above)
Comment (wuhongsong) [reply curvefs/src/client/s3/disk_cache_manager.cpp:356]: have reached an agreement that it is not need to edit

File: src/common/lru_cache.h (hunk 10 above)
Comment (wuhongsong) [reply src/common/lru_cache.h:306]: have reached an agreement that it is not need to edit, because we need traversing the list

**Comment by wuhongsong** [comment]
recheck

**Comment by wuhongsong** [comment]
recheck

File: curvefs/src/client/s3/client_s3_cache_manager.cpp [hunk 15]
```diff
@@ -2065,24 +2098,14 @@ CURVEFS_ERROR DataCache::Flush(uint64_t inodeId, bool force, bool toS3) {
...
-            }
+            auto context = std::make_shared<PutObjectAsyncContext>();
+            context->key = objectName;
+            context->buffer = data + writeOffset;
+            context->bufferSize = n;
+            context->cb = cb;
+            context->startTime = butil::cpuwide_time_us();
+            uploadTasks.emplace_back(context);
+
             if (useDiskCache) {
```
[the remark this answers is not in the document]
Comment (wuhongsong) [reply curvefs/src/client/s3/client_s3_cache_manager.cpp]: fix

File: WORKSPACE (hunk 1 above)
Comment (wuhongsong) [reply WORKSPACE]: fix

File: curvefs/src/client/s3/client_s3_cache_manager.cpp (hunk 4 above)
Comment (wuhongsong) [reply curvefs/src/client/s3/client_s3_cache_manager.cpp:952]: fix

Comment (wuhongsong) [reply curvefs/src/client/s3/client_s3_cache_manager.cpp:952]: fix

File: curvefs/src/client/s3/client_s3_cache_manager.cpp (hunk 6 above)
Comment (wuhongsong) [reply curvefs/src/client/s3/client_s3_cache_manager.cpp]: fix

File: curvefs/src/client/s3/disk_cache_manager_impl.cpp (hunk 8 above)
Comment (wuhongsong) [reply curvefs/src/client/s3/disk_cache_manager_impl.cpp]: fix

File: curvefs/src/client/BUILD [hunk 16]
```diff
@@ -28,6 +28,7 @@ cc_binary(
     ],
     deps = [
         ":fuse_client_lib",
+        "@com_google_absl//absl/memory",
```
[the remark this answers is not in the document]
Comment (wuhongsong) [reply curvefs/src/client/BUILD:31]: need use some function

File: curvefs/src/client/s3/client_s3_cache_manager.cpp [hunk 17]
```diff
@@ -932,45 +932,78 @@ void FileCacheManager::TruncateCache(uint64_t offset, uint64_t fileSize) {
 }
 
 CURVEFS_ERROR FileCacheManager::Flush(bool force, bool toS3) {
-    CURVEFS_ERROR ret;
+    CURVEFS_ERROR ret = CURVEFS_ERROR::OK;
```
[the remark this answers is not in the document]
Comment (wuhongsong) [reply curvefs/src/client/s3/client_s3_cache_manager.cpp:937]: has add todo, we can think about the plan later

File: curvefs/src/client/s3/client_s3_adaptor.cpp (hunk 5 above)
Comment (wuhongsong) [reply curvefs/src/client/s3/client_s3_adaptor.cpp]: i think yes， because it is independent

**Review by baijiaruo — APPROVED** [review]

**Review by xu-chaojie — APPROVED** [review]
