### PR TITLE
curvefs client : update inode async

### LINKED ISSUE #935: CI failover: Fuse memory is increasing while running IO
**Describe the bug (描述bug)**
image

image

**To Reproduce (复现方法)**
[global]
rw=randwrite
direct=1
iodepth=128
ioengine=libaio
bsrange=4k-4k
group_reporting
size=1G
fallocate=none
verify=md5
runtime=600
write_iops_log=str

[disk01]
filename=/home/nbs/failover/test1/1.txt
[disk02]
filename=/home/nbs/failover/test1/2.txt

**Expected behavior (期望行为)**

**Versions (各种版本)**
OS:
Compiler:
curve-mds:
curve-chunkserver:
curve-snapshotcloneserver:
curve-sdk:
nebd:
curve-nbd:

**Additional context/screenshots (更多上下文/截图)**

### PR DESCRIPTION
**Pull request by xu-chaojie**
### What problem does this PR solve?

Issue Number: close #935  

Problem Summary:

update_inode_async

### What is changed and how it works?

Update inode asynchronously， so that update inode will not block each others.

### Check List

- [x] Relevant documentation/comments is changed or added
- [x] I acknowledge that all my contributions will be made under the project's license

### CODE REVIEW

File: curvefs/src/client/rpcclient/task_excutor.cpp [hunk 1]
```diff
@@ -72,6 +79,41 @@ int TaskExecutor::DoRPCTask(std::shared_ptr<TaskContext> task) {
...
+        LOG(ERROR) << task_->TaskContextStr()
+                   << " retry times exceeds the limit";
+        done->SetRetCode(retCode);
+        return;
+    }
+
+    if (!HasValidTarget() && !GetTarget()) {
+        LOG(WARNING) << "get target fail for " << task_->TaskContextStr()
+                     << ", sleep and retry";
+        bthread_usleep(opt_.retryIntervalUS);
```
Comment (wu-hanqing) [inline curvefs/src/client/rpcclient/task_excutor.cpp:97]: what's the purpose of sleep in here? I think is conflicting with sleep in line 210

File: curvefs/src/client/rpcclient/task_excutor.cpp [hunk 2]
```diff
@@ -72,6 +79,41 @@ int TaskExecutor::DoRPCTask(std::shared_ptr<TaskContext> task) {
...
+        done->SetRetCode(retCode);
+        return;
+    }
+
+    auto channel = channelManager_->GetOrCreateChannel(
+        task_->target.metaServerID, task_->target.endPoint);
+    if (!channel) {
+        LOG(WARNING) << "GetOrCreateChannel fail for "
+                     << task_->TaskContextStr() << ", sleep and retry";
+        bthread_usleep(opt_.retryIntervalUS);
```
Comment (wu-hanqing) [inline curvefs/src/client/rpcclient/task_excutor.cpp:107]: ditto

File: curvefs/src/client/rpcclient/metaserver_client.cpp [hunk 3]
```diff
@@ -474,8 +493,101 @@ MetaStatusCode MetaServerClientImpl::UpdateInode(const Inode &inode) {
...
+}
+
+class UpdateInodeRpcDone : public MetaServerClientRpcDoneBase {
+ public:
+    UpdateInodeRpcDone(TaskExecutorDone *done,
+        const std::shared_ptr<MetaServerClientMetric> &metaserverClientMetric):
+        MetaServerClientRpcDoneBase(done, metaserverClientMetric) {}
+    virtual ~UpdateInodeRpcDone() {}
+    void Run() override;
+    UpdateInodeResponse response;
```
Comment (wu-hanqing) [inline curvefs/src/client/rpcclient/metaserver_client.cpp:507]: public data member?

File: curvefs/src/client/rpcclient/task_excutor.h [hunk 4]
```diff
@@ -44,17 +44,22 @@ using ::curvefs::client::common::ExcutorOpt;
...
 using ::curvefs::common::PartitionInfo;
+using ::curvefs::metaserver::MetaStatusCode;
 
 namespace curvefs {
 namespace client {
 namespace rpcclient {
 
+class TaskExecutorDone;
+
+MetaStatusCode ConvertToMetaStatusCode(int retcode);
```
Comment (wu-hanqing) [inline curvefs/src/client/rpcclient/task_excutor.h:55]: it seems this function is only used in .cpp file, so no need to declare it in the header file.

File: curvefs/src/client/rpcclient/task_excutor.cpp [hunk 5]
```diff
@@ -72,6 +79,41 @@ int TaskExecutor::DoRPCTask(std::shared_ptr<TaskContext> task) {
     return retCode;
 }
 
+void TaskExecutor::DoAsyncRPCTask(TaskExecutorDone *done) {
```
Comment (wu-hanqing) [inline curvefs/src/client/rpcclient/task_excutor.cpp:82]: above synchronous processing can be implemented by this asynchronous, so the main logic here doesn't have to repeat twice.

File: curvefs/src/client/rpcclient/metaserver_client.cpp [hunk 6]
```diff
@@ -474,8 +493,101 @@ MetaStatusCode MetaServerClientImpl::UpdateInode(const Inode &inode) {
...
+            vlist->CopyFrom(inode.volumeextentlist());
+            request.set_allocated_volumeextentlist(vlist);
+        }
+
+        auto *rpcDone = new UpdateInodeRpcDone(taskExecutorDone,
+            metaserverClientMetric_);
+
+        curvefs::metaserver::MetaServerService_Stub stub(channel);
+        stub.UpdateInode(cntl, &request, &rpcDone->response, rpcDone);
+        return MetaStatusCode::OK;
```
Comment (wu-hanqing) [inline curvefs/src/client/rpcclient/metaserver_client.cpp:582]: return value is redundant

File: curvefs/src/client/rpcclient/metaserver_client.cpp [hunk 7]
```diff
@@ -539,14 +651,104 @@ MetaStatusCode MetaServerClientImpl::GetOrModifyS3ChunkInfo(
...
+        request.set_returns3chunkinfomap(false);
+        *(request.mutable_s3chunkinfoadd()) = s3ChunkInfos;
+
+        auto *rpcDone = new GetOrModifyS3ChunkInfoRpcDone(taskExecutorDone,
+            metaserverClientMetric_);
+
+        curvefs::metaserver::MetaServerService_Stub stub(channel);
+        stub.GetOrModifyS3ChunkInfo(
+            cntl, &request, &rpcDone->response, rpcDone);
+        return MetaStatusCode::OK;
```
Comment (wu-hanqing) [inline curvefs/src/client/rpcclient/metaserver_client.cpp:737]: ditto

File: curvefs/src/client/inode_wrapper.cpp [hunk 8]
```diff
@@ -93,7 +148,28 @@ CURVEFS_ERROR InodeWrapper::Sync() {
...
+}
+
+void InodeWrapper::FlushS3ChunkInfoAsync() {
+    if (!s3ChunkInfoAdd_.empty()) {
+        LockSyncingS3ChunkInfo();
+         auto *done = new GetOrModifyS3ChunkInfoAsyncDone(shared_from_this());
+        metaClient_->GetOrModifyS3ChunkInfoAsync(
+            inode_.fsid(), inode_.inodeid(), s3ChunkInfoAdd_,
+            done);
+        s3ChunkInfoAdd_.clear();
```
Comment (wu-hanqing) [inline curvefs/src/client/inode_wrapper.cpp:167]: why not move it when calling `GetOrModifyS3ChunkInfoAsync`?

File: curvefs/src/client/inode_wrapper.cpp [hunk 9]
```diff
@@ -93,7 +148,28 @@ CURVEFS_ERROR InodeWrapper::Sync() {
     return CURVEFS_ERROR::OK;
 }
 
-CURVEFS_ERROR InodeWrapper::Refresh() {
+void InodeWrapper::FlushAttrAsync() {
+    if (dirty_) {
+        LockSyncingInode();
+        auto *done = new UpdateInodeAsyncDone(shared_from_this());
+        metaClient_->UpdateInodeAsync(inode_, done);
+        dirty_ = false;
```
Comment (ilixiaocui) [inline curvefs/src/client/inode_wrapper.cpp:156]: dirty_=false should update in done?

File: curvefs/src/client/inode_wrapper.cpp (hunk 8 above)
Comment (ilixiaocui) [inline curvefs/src/client/inode_wrapper.cpp:167]: should clear it in done?

File: curvefs/src/client/inode_wrapper.h [hunk 10]
```diff
@@ -220,18 +238,51 @@ class InodeWrapper {
             inode_.mutable_s3chunkinfomap());
     }
 
+    void MarkInodeError() {
+        // TODO(xuchaojie) : when inode is marked error, prevent futher write.
+        status_ = -1;
```
Comment (ilixiaocui) [inline curvefs/src/client/inode_wrapper.h:243]: enum status {
}?

File: curvefs/src/client/rpcclient/metaserver_client.cpp [hunk 11]
```diff
@@ -53,7 +53,26 @@ MetaStatusCode MetaServerClientImpl::Init(
 #define RPCTask                                                                \
     [&](LogicPoolID poolID, CopysetID copysetID, PartitionID partitionID,      \
         uint64_t txId, uint64_t applyIndex, brpc::Channel * channel,           \
-        brpc::Controller * cntl) -> int
+        brpc::Controller * cntl, TaskExecutorDone *taskExecutorDone) -> int
+
+#define AsyncRPCTask                                                           \
```
Comment (ilixiaocui) [inline curvefs/src/client/rpcclient/metaserver_client.cpp:58]: AsyncRPCTask is defined same as RPCTask

File: curvefs/src/client/rpcclient/metaserver_client.cpp [hunk 12]
```diff
@@ -539,14 +651,104 @@ MetaStatusCode MetaServerClientImpl::GetOrModifyS3ChunkInfo(
...
+    MetaStatusCode ret = response.statuscode();
+    if (ret != MetaStatusCode::OK) {
+        LOG(WARNING) << "GetOrModifyS3ChunkInfo, inodeId: "
+                     << taskCtx->inodeID
+                     << ", fsId: " << taskCtx->fsID
+                     << ", errorcode: " << ret
+                     << ", errmsg: " << MetaStatusCode_Name(ret);
+        done_->SetRetCode(ret);
+        return;
+    } else if (response.has_appliedindex()) {
```
Comment (ilixiaocui) [inline curvefs/src/client/rpcclient/metaserver_client.cpp:695]: why not judge s3ChunkInfoMap in GetOrModifyS3ChunkInfoResponse?

File: curvefs/src/client/rpcclient/task_excutor.cpp (hunk 5 above)
Comment (ilixiaocui) [reply curvefs/src/client/rpcclient/task_excutor.cpp:82]: yeap. sync and async can be solved in same DoRPCTask distinguished by whether done is null.

File: curvefs/src/client/rpcclient/metaserver_client.cpp [hunk 13]
```diff
@@ -474,8 +493,101 @@ MetaStatusCode MetaServerClientImpl::UpdateInode(const Inode &inode) {
...
+    brpc::ClosureGuard done_guard(done_);
+    auto taskCtx = done_->GetTaskExcutor()->GetTaskCxt();
+    auto& cntl = taskCtx->cntl_;
+    auto metaCache = done_->GetTaskExcutor()->GetMetaCache();
+    if (cntl.Failed()) {
+        metaserverClientMetric_->updateInode.eps.count << 1;
+        LOG(WARNING) << "UpdateInode Failed, errorcode = "
+                     << cntl.ErrorCode()
+                     << ", error content:" << cntl.ErrorText()
+                     << ", log id = " << cntl.log_id();
```
[the remark this answers is not in the document]
Comment (xu-chaojie) [reply curvefs/src/client/rpcclient/metaserver_client.cpp:521]: done

File: curvefs/src/client/rpcclient/task_excutor.cpp (hunk 1 above)
Comment (xu-chaojie) [reply curvefs/src/client/rpcclient/task_excutor.cpp:97]: done

File: curvefs/src/client/rpcclient/task_excutor.cpp (hunk 2 above)
Comment (xu-chaojie) [reply curvefs/src/client/rpcclient/task_excutor.cpp:107]: done

File: curvefs/src/client/rpcclient/metaserver_client.cpp (hunk 3 above)
Comment (xu-chaojie) [reply curvefs/src/client/rpcclient/metaserver_client.cpp:507]: yes

File: curvefs/src/client/rpcclient/task_excutor.h (hunk 4 above)
Comment (xu-chaojie) [reply curvefs/src/client/rpcclient/task_excutor.h:55]: it was used by two different cpp files

File: curvefs/src/client/rpcclient/task_excutor.cpp (hunk 5 above)
Comment (xu-chaojie) [reply curvefs/src/client/rpcclient/task_excutor.cpp:82]: no,  the synchronous will retry in this function, but asynchronous way retry by closure return, they not same

File: curvefs/src/client/rpcclient/metaserver_client.cpp (hunk 7 above)
Comment (xu-chaojie) [reply curvefs/src/client/rpcclient/metaserver_client.cpp:737]: ditto

File: curvefs/src/client/inode_wrapper.cpp (hunk 8 above)
Comment (xu-chaojie) [reply curvefs/src/client/inode_wrapper.cpp:167]: s3ChunkInfoAdd_ should clear here， so that new s3chunkinfo can add to it when new write come

File: curvefs/src/client/inode_wrapper.cpp (hunk 9 above)
Comment (xu-chaojie) [reply curvefs/src/client/inode_wrapper.cpp:156]: no, should be update here, so when new write come, it can be set dirty again

File: curvefs/src/client/inode_wrapper.cpp (hunk 8 above)
Comment (xu-chaojie) [reply curvefs/src/client/inode_wrapper.cpp:167]: s3ChunkInfoAdd_ should clear here， so that new s3chunkinfo can add to it when new write come

File: curvefs/src/client/inode_wrapper.h (hunk 10 above)
Comment (xu-chaojie) [reply curvefs/src/client/inode_wrapper.h:243]: done

File: curvefs/src/client/rpcclient/metaserver_client.cpp (hunk 11 above)
Comment (xu-chaojie) [reply curvefs/src/client/rpcclient/metaserver_client.cpp:58]: not the same, AsyncRPCTask is "capture  by copy"

File: curvefs/src/client/rpcclient/metaserver_client.cpp (hunk 12 above)
Comment (xu-chaojie) [reply curvefs/src/client/rpcclient/metaserver_client.cpp:695]: judge what? it can be empty.

**Review by wu-hanqing — APPROVED** [review]

**Review by ilixiaocui — APPROVED** [review]
