### PR TITLE
curvefs/client: fixed concurrent rename causes txid to be overwritten

### LINKED ISSUE #855: curvefs: elk file read  error
**Describe the bug (描述bug)**
elk read file error，as follows：
org.apache.lucene.index.CorruptIndexException: Problem reading index. (resource=/srv/nos/elk4/nodes/0/indices/tl-n7BCCSPqxxRXyoiFDcg/9/index
/_b.kdm)
but stat file is exist
stat  /srv/nos/elk4/nodes/0/indices/tl-n7BCCSPqxxRXyoiFDcg/9/index/_b.kdm
  File: /srv/nos/elk4/nodes/0/indices/tl-n7BCCSPqxxRXyoiFDcg/9/index/_b.kdm
  Size: 363             Blocks: 1          IO Block: 65536  regular file
Device: 28h/40d Inode: 33574943    Links: 1
Access: (0644/-rw-r--r--)  Uid: ( 9767/elasticsearch)   Gid: ( 9767/elasticsearch)
Access: 2021-12-15 11:16:23.480512041 +0800
Modify: 2021-12-15 11:16:22.871698469 +0800
Change: 2021-12-15 11:16:23.480512041 +0800

**To Reproduce (复现方法)**

**Expected behavior (期望行为)**

**Versions (各种版本)**
OS:
Compiler:
curve-mds:
curve-chunkserver:
curve-snapshotcloneserver:
curve-sdk:
nebd:
curve-nbd:

**Additional context/screenshots (更多上下文/截图)**

### PR DESCRIPTION
**Pull request by Wine93**
when two rename operators executed in the different diretories at the same time,
the second one maybe get the old txid to prepare, it lets transaction manager
beleive that the previous one is failed and to rollback it, it will causes the
first operation prepare items lost even if itself return success (#855).

### What problem does this PR solve?

Issue Number: close #855

Problem Summary:

### What is changed and how it works?

What's Changed:

How it Works:

Side effects(Breaking backward compatibility? Performance regression?): 

### Check List

- [ ] Relevant documentation/comments is changed or added
- [ ] I acknowledge that all my contributions will be made under the project's license

### CODE REVIEW

**Comment by Wine93** [comment]
recheck

**Comment by Wine93** [comment]
recheck

**Comment by Wine93** [comment]
recheck

**Comment by Wine93** [comment]
recheck

**Comment by Wine93** [comment]
recheck

**Comment by Wine93** [comment]
recheck

**Comment by Wine93** [comment]
recheck

**Comment by YunhuiChen** [comment]
recheck

**Comment by YunhuiChen** [comment]
recheck

**Comment by Wine93** [comment]
recheck

**Comment by YunhuiChen** [comment]
recheck

**Comment by YunhuiChen** [comment]
recheck

**Comment by Wine93** [comment]
recheck

**Comment by YunhuiChen** [comment]
recheck

File: curvefs/src/client/s3/disk_cache_manager.cpp [hunk 1]
```diff
@@ -41,6 +41,9 @@ DiskCacheManager::DiskCacheManager(std::shared_ptr<PosixWrapper> posixWrapper,
     isRunning_ = false;
     usedBytes_ = 0;
     diskFsUsedRatio_ = 0;
+    fullRatio_ = 0;
+    safeRatio_ = 0;
+    maxUsableSpaceBytes_ = 0;
```
Comment (xu-chaojie) [inline curvefs/src/client/s3/disk_cache_manager.cpp:46]: Why change here？

**Review by xu-chaojie — APPROVED** [review]

File: curvefs/src/client/s3/disk_cache_manager.cpp (hunk 1 above)
Comment (Wine93) [reply curvefs/src/client/s3/disk_cache_manager.cpp:46]: > Why change here？

There is a bug in this test case.

**Review by baijiaruo — APPROVED** [review]
