### PR TITLE
curvefs/client:fix curve-fuse coredump

### LINKED ISSUE #720: curve-fuse coredump
**Describe the bug (描述bug)**

image

**To Reproduce (复现方法)**

**Expected behavior (期望行为)**

**Versions (各种版本)**
OS:
Compiler:
curve-mds:
curve-chunkserver:
curve-snapshotcloneserver:
curve-sdk:
nebd:
curve-nbd:

**Additional context/screenshots (更多上下文/截图)**

### PR DESCRIPTION
**Pull request by baijiaruo**
### What problem does this PR solve?

Issue Number: close #720  

Problem Summary:

### What is changed and how it works?

What's Changed:

How it Works:

Side effects(Breaking backward compatibility? Performance regression?): 

### Check List

- [ ] Relevant documentation/comments is changed or added
- [ ] I acknowledge that all my contributions will be made under the project's license

### CODE REVIEW

**Review by xu-chaojie — APPROVED** [review]

File: curvefs/src/client/s3/client_s3_cache_manager.cpp [hunk 1]
```diff
@@ -189,7 +189,7 @@ void FileCacheManager::WriteChunk(uint64_t index, uint64_t chunkPos,
             << ", chunkPos: " << chunkPos;
     ChunkCacheManagerPtr chunkCacheManager =
         FindOrCreateChunkCacheManager(index);
-    WriteLockGuard readLockGuard(chunkCacheManager->rwLockChunk_);  // todo
+    WriteLockGuard writeLockGuard(chunkCacheManager->rwLockChunk_);  // todo
```
Comment (xu-chaojie) [inline curvefs/src/client/s3/client_s3_cache_manager.cpp:192]: todo what ?

Comment (baijiaruo) [reply curvefs/src/client/s3/client_s3_cache_manager.cpp:192]: this lock is too big，but safe

**Review by wu-hanqing — APPROVED** [review]
