### PR TITLE
curvefs/client: fix bug issue

### LINKED ISSUE #1213: Description Echo data is corrupted after being transferred to multiple mounted files
**Describe the bug (描述bug)**

**To Reproduce (复现方法)**
1、mount test1 and test10
2、vdbench test test1
3、run test.sh
#/bin/bash
for i in `seq 1 100`;do 
	echo "test $i" >> /home/nbs/failover/test1/cyh
	cat /home/nbs/failover/test1/cyh
	cat /home/nbs/failover/test10/cyh
	sleep 0.5
	echo "test $i" >> /home/nbs/failover/test10/cyh
	cat /home/nbs/failover/test1/cyh
	cat /home/nbs/failover/test10/cyh
	sleep 0.5
done
4、cyh is :
image

**Expected behavior (期望行为)**

**Versions (各种版本)**
OS:
Compiler:
curve-mds:
curve-chunkserver:
curve-snapshotcloneserver:
curve-sdk:
nebd:
curve-nbd:

**Additional context/screenshots (更多上下文/截图)**

### PR DESCRIPTION
**Pull request by ilixiaocui**
### What problem does this PR solve?

Issue Number: close #1213 #1209 #1201 #1197  

Problem Summary:

### What is changed and how it works?

What's Changed:

How it Works:

Side effects(Breaking backward compatibility? Performance regression?): 

### Check List

- [ ] Relevant documentation/comments is changed or added
- [ ] I acknowledge that all my contributions will be made under the project's license

### CODE REVIEW

**Comment by ilixiaocui** [comment]
recheck

File: curvefs/src/client/main.c [hunk 1]
```diff
@@ -49,6 +49,7 @@ static const struct fuse_lowlevel_ops curve_ll_oper = {
     .release    = FuseOpRelease,
```
Comment (xu-chaojie) [inline curvefs/src/client/main.c:49]: If you remove the FuseOpRelease impliment,  ”.release = FuseOpRelease“ also should remove.

File: curvefs/src/client/dentry_cache_manager.cpp [hunk 2]
```diff
@@ -38,8 +46,10 @@ using NameLockGuard = ::curve::common::GenericNameLockGuard<Mutex>;
 
 void DentryCacheManagerImpl::InsertOrReplaceCache(const Dentry &dentry) {
     std::string key = GetDentryCacheKey(dentry.parentinodeid(), dentry.name());
-    NameLockGuard lock(nameLock_, key);
-    dCache_->Put(key, dentry);
+    if (!curvefs::client::common::FLAGS_enableCto) {
```
Comment (baijiaruo) [inline curvefs/src/client/dentry_cache_manager.cpp:49]: In order to avoid adding FLAGS_enableCto everywhere, is it better to use a cto DentryCacheManagerImpl class

File: curvefs/src/client/fuse_s3_client.cpp [hunk 3]
```diff
@@ -254,53 +254,47 @@ CURVEFS_ERROR FuseS3Client::Truncate(Inode *inode, uint64_t length) {
...
-        LOG(ERROR) << "FuseOpRelease, inodeManager get inode fail, ret = "
-                   << ret << ", inodeid = " << ino;
+        LOG(ERROR) << "FuseOpFlush, inodeManager get inode fail, ret = "
+                   << ret << ", ino: " << ino;
         return ret;
     }
 
     ::curve::common::UniqueLock lgGuard = inodeWrapper->GetUniqueLock();
-    // if enableCto, need sync inode meta
-    if (::curvefs::client::common::FLAGS_enableCto) {
```
Comment (baijiaruo) [inline curvefs/src/client/fuse_s3_client.cpp:283]: Do you need to flush the inode without cto?

File: curvefs/src/client/s3/client_s3_cache_manager.cpp [hunk 4]
```diff
@@ -310,9 +310,16 @@ int FileCacheManager::Read(uint64_t inodeId, uint64_t offset, uint64_t length,
             std::vector<S3ReadRequest> totalS3Requests;
             auto iter = totalRequests.begin();
             uint64_t fileLen;
+            butil::Timer timer;
```
Comment (baijiaruo) [inline curvefs/src/client/s3/client_s3_cache_manager.cpp:313]: Performance test code?

Comment (ilixiaocui) [reply curvefs/src/client/s3/client_s3_cache_manager.cpp:313]: fix

File: curvefs/src/client/s3/client_s3_cache_manager.cpp [hunk 5]
```diff
@@ -310,9 +310,16 @@ int FileCacheManager::Read(uint64_t inodeId, uint64_t offset, uint64_t length,
...
+            timer.start();
             {
+                butil::Timer timer;
+                timer.start();
                 ::curve::common::UniqueLock lgGuard =
                     inodeWrapper->GetUniqueLock();
+                timer.stop();
+                LOG(INFO) << "GenerateS3Request for inodeid: " << inode_
```
Comment (xu-chaojie) [inline curvefs/src/client/s3/client_s3_cache_manager.cpp:321]: DEVLOG?

File: curvefs/src/client/s3/client_s3_cache_manager.cpp [hunk 6]
```diff
@@ -339,6 +346,9 @@ int FileCacheManager::Read(uint64_t inodeId, uint64_t offset, uint64_t length,
                                            s3Requests.end());
                 }
             }
+            timer.stop();
+            LOG(INFO) << "GenerateS3Request for inodeid: " << inode_
```
Comment (xu-chaojie) [inline curvefs/src/client/s3/client_s3_cache_manager.cpp:350]: DEVLOG?

File: curvefs/src/client/fuse_s3_client.cpp (hunk 3 above)
Comment (ilixiaocui) [reply curvefs/src/client/fuse_s3_client.cpp:283]: Keep consistent with FuseOpFsync.

File: curvefs/src/client/s3/client_s3_cache_manager.cpp (hunk 6 above)
Comment (ilixiaocui) [reply curvefs/src/client/s3/client_s3_cache_manager.cpp:350]: remove test log

**Review by baijiaruo — APPROVED** [review]

**Review by xu-chaojie — APPROVED** [review]

**Comment by ilixiaocui** [comment]
recheck
