### PR TITLE
curvefs/rpcclient: fix io hang when mds host power down

### LINKED ISSUE #732: shutdown one etcd\mds\metaserver,  io hang
**Describe the bug (描述bug)**

shutdown one etcd\mds\metaserver,  io hang
**To Reproduce (复现方法)**
1、write vdbench
2、reboot one host, have (etcd \ mds \ metaserver)
3、io hange 4-5 minutes

**Expected behavior (期望行为)**

**Versions (各种版本)**
OS:
Compiler:
curve-mds:
curve-chunkserver:
curve-snapshotcloneserver:
curve-sdk:
nebd:
curve-nbd:

**Additional context/screenshots (更多上下文/截图)**
image
image

### PR DESCRIPTION
**Pull request by wu-hanqing**
### What problem does this PR solve?

Issue Number: close #732 

Problem Summary: https://github.com/opencurve/curve/issues/732#issuecomment-979659922

### What is changed and how it works?

What's Changed: lower down some configurations

How it Works:

Side effects(Breaking backward compatibility? Performance regression?): 

### Check List

- [x] Relevant documentation/comments is changed or added
- [x] I acknowledge that all my contributions will be made under the project's license

### CODE REVIEW

File: curvefs/src/client/rpcclient/mds_client.cpp [hunk 1]
```diff
@@ -94,7 +94,10 @@ FSStatusCode MdsClientImpl::CreateFsS3(const std::string &fsName,
 
         return ret;
     };
-    return ReturnError(rpcexcutor_.DoRPCTask(task, mdsOpt_.mdsMaxRetryMS));
+
+    // manually set to a large timeout, because create fs may very slow
```
Comment (ilixiaocui) [inline curvefs/src/client/rpcclient/mds_client.cpp:98]: // TODO
createfs will remove in the feature.

File: curvefs/conf/client.conf [hunk 2]
```diff
@@ -57,7 +56,7 @@ extentManager.preAllocSize=65536
 
 #### brpc
 # close socket after defer.close.second
-rpc.defer.close.second=600
+rpc.defer.close.second=1
```
Comment (ilixiaocui) [inline curvefs/conf/client.conf:59]: defer set to a long time for reuse, Will this be disconnected under abnormal conditions?

File: curvefs/src/client/rpcclient/mds_client.cpp (hunk 1 above)
Comment (wu-hanqing) [reply curvefs/src/client/rpcclient/mds_client.cpp:98]: line 78 has a TODO about this

File: curvefs/conf/client.conf (hunk 2 above)
Comment (wu-hanqing) [reply curvefs/conf/client.conf:59]: it's not, there is an atomic variable that stores currentWorkingMds, and only when RPC succeeded atomic get updated.

so, next `AllocS3ChunkId` will send RPC to power down MDS firstly, because no one succeeds sending RPC to MDS and currentWorkingMds still stores the power down MDS

**Review by SeanHai — APPROVED** [review]

**Review by ilixiaocui — APPROVED** [review]
