### PR TITLE
curvefs/client: refactor the code read data from s3info

### LINKED ISSUE #673: curvefs: data inconsistent and io error occurs while runing vdbench
**Describe the bug (描述bug)**
Vdbench reading and writing are inconsistent and io error
image

**To Reproduce (复现方法)**
use vdbench test,profile is：
fsd=fsd1,anchor=/home/nbs/failover/test2,depth=1,width=10,files=10,sizes=(100m,0),shared=yes,openflags=o_direct
fwd=fwd1,fsd=fsd1,threads=10,xfersize=(512,20,4k,20,64k,20,512k,20,1024k,20),fileio=random,fileselect=random,rdpct=50
rd=rd1,fwd=fwd*,fwdrate=max,format=restart,elapsed=1200,interval=1

**Expected behavior (期望行为)**
test success

**Versions (各种版本)**
OS: 4.9.65-netease
Compiler:
curve-mds: 
curve-chunkserver:
curve-snapshotcloneserver:
curve-sdk:
nebd:
curve-nbd:

**Additional context/screenshots (更多上下文/截图)**

### PR DESCRIPTION
**Pull request by baijiaruo**
### What problem does this PR solve?

Issue Number: close #673 

Problem Summary:

### What is changed and how it works?

What's Changed:

How it Works:

Side effects(Breaking backward compatibility? Performance regression?): 

### Check List

- [ ] Relevant documentation/comments is changed or added
- [ ] I acknowledge that all my contributions will be made under the project's license

### CODE REVIEW

**Comment by baijiaruo** [comment]
recheck

File: curvefs/src/client/s3/client_s3_cache_manager.cpp [hunk 1]
```diff
@@ -506,14 +503,225 @@ void FileCacheManager::PrefetchS3Objs(std::vector<std::string> prefetchObjs) {
...
+    uint64_t chunkSize = s3ClientAdaptor_->GetChunkSize();
+    std::map<uint64_t, ReadRequest> readRequests;  // first is chunkPos
+
+    VLOG(9) << "GenerateS3Request start request index:" << request.index
+            << ",chunkPos:" << request.chunkPos << ",len:" << request.len
+            << ",bufOffset:" << request.bufOffset;
+    readRequests.emplace(request.chunkPos, request);
+    int i = s3ChunkInfoList.s3chunks_size() - 1;
+    for (; i >= 0; i--) {
+        S3ChunkInfo s3ChunkInfo = s3ChunkInfoList.s3chunks(i);
```
Comment (ilixiaocui) [inline curvefs/src/client/s3/client_s3_cache_manager.cpp:529]: const S3ChunkInfo& s3ChunkInfo = s3ChunkInfoList.s3chunks(i);

File: curvefs/src/client/s3/client_s3_cache_manager.cpp [hunk 2]
```diff
@@ -506,14 +503,225 @@ void FileCacheManager::PrefetchS3Objs(std::vector<std::string> prefetchObjs) {
...
+        uint64_t chunkInfoOffset = s3ChunkInfo.offset();
```
Comment (ilixiaocui) [inline curvefs/src/client/s3/client_s3_cache_manager.cpp:530]: No need to assign, just use s3ChunkInfo.offset() and s3ChunkInfo.len()

File: curvefs/src/client/s3/client_s3_cache_manager.cpp [hunk 3]
```diff
@@ -506,14 +503,225 @@ void FileCacheManager::PrefetchS3Objs(std::vector<std::string> prefetchObjs) {
...
+        uint64_t chunkInfoLen = s3ChunkInfo.len();
+        std::vector<ReadRequest> addReadRequests;
+        std::vector<uint64_t> deletingReq;
+        uint64_t readOffset;
+        auto readRequestIter = readRequests.begin();
+        for (; readRequestIter != readRequests.end(); readRequestIter++) {
+            S3ReadRequest s3Request;
+            uint64_t offset = readRequestIter->second.index * chunkSize +
```
Comment (ilixiaocui) [inline curvefs/src/client/s3/client_s3_cache_manager.cpp:538]: Calculations are encapsulated in functions.
ChunkOffsetTOFileOffset()

File: curvefs/src/client/s3/client_s3_cache_manager.cpp [hunk 4]
```diff
@@ -506,14 +503,225 @@ void FileCacheManager::PrefetchS3Objs(std::vector<std::string> prefetchObjs) {
...
+                    << s3ChunkInfo.chunkid()
+                    << ",offset:" << s3ChunkInfo.offset()
+                    << ",len:" << s3ChunkInfo.len()
+                    << ",compaction:" << s3ChunkInfo.compaction()
+                    << ",zero:" << s3ChunkInfo.zero();
+            /*
+                -----    read block
+                       ------  S3ChunkInfo
+            */
+            if (offset + length <= chunkInfoOffset) {
```
Comment (ilixiaocui) [inline curvefs/src/client/s3/client_s3_cache_manager.cpp:558]: Split into functions

File: curvefs/src/client/s3/client_s3_cache_manager.cpp (hunk 2 above)
Comment (baijiaruo) [reply curvefs/src/client/s3/client_s3_cache_manager.cpp:530]: avoid too many function calls

File: curvefs/src/client/s3/client_s3_cache_manager.cpp (hunk 4 above)
Comment (baijiaruo) [reply curvefs/src/client/s3/client_s3_cache_manager.cpp:559]: add HandleReadRequest encapsulate

File: curvefs/src/client/s3/client_s3_cache_manager.cpp [hunk 5]
```diff
@@ -1126,15 +1212,19 @@ DataCachePtr ChunkCacheManager::FindWriteableDataCache(
...
             for (; iterDel != waitDelVec.end(); iterDel++) {
                 auto iter = dataWCacheMap_.find(*iterDel);
-
+                VLOG(9) << "delete data cache chunkPos:"
+                        << iter->second->GetChunkPos()
+                        << ", len:" << iter->second->GetLen()
+                        << ",inode:" << inodeId << ",chunkIndex:" << index_;
                 s3ClientAdaptor_->GetFsCacheManager()->DataCacheNumFetchSub(1);
-                VLOG(9) << "FindWriteableDataCache() DataCacheByteDec1 len:"
+                VLOG(9) << "GFindWriteableDataCache() DataCacheByteDec1 len:"
```
Comment (ilixiaocui) [inline curvefs/src/client/s3/client_s3_cache_manager.cpp:1227]: what does GFind mean?

File: curvefs/src/client/s3/client_s3_cache_manager.cpp [hunk 6]
```diff
@@ -1152,16 +1242,19 @@ ChunkCacheManager::CreateWriteDataCache(S3ClientAdaptorImpl *s3ClientAdaptor,
                                         const char *data) {
     DataCachePtr dataCache =
         std::make_shared<DataCache>(s3ClientAdaptor, this, chunkPos, len, data);
-    VLOG(9) << "CreateWriteDataCache chunkPos:" << chunkPos << ", len:" << len;
+    VLOG(9) << "CreateWriteDataCache chunkPos:" << chunkPos << ", len:" << len
+            << ",chunkIndex:" << index_;
     WriteLockGuard writeLockGuard(rwLockWrite_);
 
-    dataWCacheMap_.emplace(chunkPos, dataCache);
+    auto ret = dataWCacheMap_.emplace(chunkPos, dataCache);
```
Comment (ilixiaocui) [inline curvefs/src/client/s3/client_s3_cache_manager.cpp:1249]: fsmanagermap and filemanagermap alse need check return value

File: curvefs/src/client/s3/client_s3_cache_manager.cpp [hunk 7]
```diff
@@ -1274,28 +1371,52 @@ CURVEFS_ERROR ChunkCacheManager::Flush(uint64_t inodeId, bool force) {
         }
         if (ret == CURVEFS_ERROR::OK) {
             if (!iter->second->IsDirty()) {
-                AddReadDataCache(iter->second);
-                ReleaseWriteDataCache(iter->first, iter->second->GetLen());
+                // AddReadDataCache(iter->second);
```
Comment (ilixiaocui) [inline curvefs/src/client/s3/client_s3_cache_manager.cpp:1374]: delete it

File: curvefs/src/client/s3/client_s3_cache_manager.cpp [hunk 8]
```diff
@@ -1333,8 +1457,11 @@ void DataCache::Write(uint64_t chunkPos, uint64_t len, const char *data,
                            (*iter)->GetData() +
                                (chunkPos + len - (*iter)->GetChunkPos()),
                            totalSize - len);
+                    chunkCacheManager_->rwLockWrite_.WRLock();
                     Swap(newDatabuf, totalSize);
                     chunkPos_ = chunkPos;
+                    chunkCacheManager_->UpdateWrteCacheMap(oldChunkPos);
```
Comment (ilixiaocui) [inline curvefs/src/client/s3/client_s3_cache_manager.cpp:1463]: lock can be placed in function UpdateWrteCacheMap

File: curvefs/src/client/s3/client_s3_cache_manager.cpp [hunk 9]
```diff
@@ -1152,16 +1242,19 @@ ChunkCacheManager::CreateWriteDataCache(S3ClientAdaptorImpl *s3ClientAdaptor,
                                         const char *data) {
     DataCachePtr dataCache =
         std::make_shared<DataCache>(s3ClientAdaptor, this, chunkPos, len, data);
-    VLOG(9) << "CreateWriteDataCache chunkPos:" << chunkPos << ", len:" << len;
+    VLOG(9) << "CreateWriteDataCache chunkPos:" << chunkPos << ", len:" << len
```
Comment (wu-hanqing) [inline curvefs/src/client/s3/client_s3_cache_manager.cpp:1245]: it seams current function is no need to return a value

File: curvefs/src/client/s3/client_s3_cache_manager.cpp [hunk 10]
```diff
@@ -1309,8 +1430,11 @@ void DataCache::Write(uint64_t chunkPos, uint64_t len, const char *data,
             memcpy(newDatabuf, data, len);
             memcpy(newDatabuf + len, data_ + (chunkPos + len - chunkPos_),
                    totalSize - len);
+            chunkCacheManager_->rwLockWrite_.WRLock();
             Swap(newDatabuf, totalSize);
             chunkPos_ = chunkPos;
+            chunkCacheManager_->UpdateWrteCacheMap(oldChunkPos);
+            chunkCacheManager_->rwLockWrite_.Unlock();
```
Comment (wu-hanqing) [inline curvefs/src/client/s3/client_s3_cache_manager.cpp:1437]: why not remove all overlap data cache including the current one from chunkcachemanager firstly, then put it back to the manager after writing

File: curvefs/src/client/rpcclient/metaserver_client.cpp [hunk 11]
```diff
@@ -396,8 +396,14 @@ MetaStatusCode MetaServerClientImpl::GetInode(uint32_t fsId, uint64_t inodeid,
...
-        VLOG(6) << "GetInode success, request: " << request.DebugString()
-                << "response: " << response.DebugString();
+        /*VLOG(6) << "GetInode success, request: " << request.DebugString()
+                << "response: " << response.DebugString();*/
+        auto &s3chunkinfoMap = response.inode().s3chunkinfomap();
+        for (auto &item : s3chunkinfoMap) {
+            VLOG(9) << "inodeInfo, inodeId:" << inodeid
+                    << ",s3chunkinfo item key:" << item.first
+                    << ", value:" << item.second.DebugString();
+        }
```
[the remark this answers is not in the document]
Comment (baijiaruo) [reply curvefs/src/client/rpcclient/metaserver_client.cpp:406]: problem analysis need it

File: curvefs/src/client/s3/client_s3_cache_manager.cpp [hunk 12]
```diff
@@ -427,7 +425,7 @@ int FileCacheManager::HandleReadRequest(
 
     for (auto &dataCache : DataCacheVec) {
         VLOG(9) << "add read data cache start";
-        dataCache.first->AddReadDataCache(dataCache.second);
+        // dataCache.first->AddReadDataCache(dataCache.second);
```
[the remark this answers is not in the document]
Comment (baijiaruo) [reply curvefs/src/client/s3/client_s3_cache_manager.cpp:428]: this must need，if hanqing pr is submit

File: curvefs/src/client/s3/client_s3_cache_manager.cpp [hunk 13]
```diff
@@ -506,176 +504,256 @@ void FileCacheManager::PrefetchS3Objs(std::vector<std::string> prefetchObjs) {
...
+                                         uint64_t fsId, uint64_t inodeId) {
+    // first is chunkPos, user read request is split into multiple,
+    // and emplace in the readRequests;
+    std::map<uint64_t, ReadRequest> readRequests;
+
+    VLOG(9) << "GenerateS3Request start request index:" << request.index
+            << ",chunkPos:" << request.chunkPos << ",len:" << request.len
+            << ",bufOffset:" << request.bufOffset;
+    readRequests.emplace(request.chunkPos, request);
+    int i = s3ChunkInfoList.s3chunks_size() - 1;
```
[the remark this answers is not in the document]
Comment (baijiaruo) [reply curvefs/src/client/s3/client_s3_cache_manager.cpp:698]: I think this cause for statement is too long

File: curvefs/src/client/s3/client_s3_cache_manager.cpp [hunk 14]
```diff
@@ -745,12 +823,12 @@ std::vector<ObjectChunkInfo> FileCacheManager::GetReadChunks(
...
 
-std::vector<ObjectChunkInfo> FileCacheManager::SortByOffset(
-    std::vector<ObjectChunkInfo> chunks) {
+std::vector<ObjectChunkInfo>
+FileCacheManager::SortByOffset(std::vector<ObjectChunkInfo> chunks) {
     std::sort(chunks.begin(), chunks.end(),
-    [](ObjectChunkInfo a, ObjectChunkInfo b) {
-        return a.s3ChunkInfo.offset() < b.s3ChunkInfo.offset();
-    });
+              [](ObjectChunkInfo a, ObjectChunkInfo b) {
```
[the remark this answers is not in the document]
Comment (baijiaruo) [reply curvefs/src/client/s3/client_s3_cache_manager.cpp:829]: this function is deleted

File: curvefs/src/client/s3/client_s3_cache_manager.cpp [hunk 15]
```diff
@@ -828,6 +906,7 @@ void FileCacheManager::ReadChunk(uint64_t index, uint64_t chunkPos,
                                  std::vector<ReadRequest> *requests) {
     ChunkCacheManagerPtr chunkCacheManager =
         FindOrCreateChunkCacheManager(index);
+    curve::common::LockGuard lg(chunkCacheManager->mtx_);
```
[the remark this answers is not in the document]
Comment (baijiaruo) [reply curvefs/src/client/s3/client_s3_cache_manager.cpp:909]: this function is deleted

File: curvefs/src/client/s3/client_s3_cache_manager.cpp (hunk 5 above)
Comment (baijiaruo) [reply curvefs/src/client/s3/client_s3_cache_manager.cpp:1227]: wrong letter

File: curvefs/src/client/s3/client_s3_cache_manager.cpp (hunk 9 above)
Comment (baijiaruo) [reply curvefs/src/client/s3/client_s3_cache_manager.cpp:1245]: why？

File: curvefs/src/client/s3/client_s3_cache_manager.cpp (hunk 10 above)
Comment (baijiaruo) [reply curvefs/src/client/s3/client_s3_cache_manager.cpp:1437]: I didn't understand

File: curvefs/src/client/s3/client_s3_cache_manager.cpp (hunk 8 above)
Comment (baijiaruo) [reply curvefs/src/client/s3/client_s3_cache_manager.cpp:1463]: it must passed A lot of arguments to UpdateWrteCacheMap

File: curvefs/src/client/s3/client_s3_cache_manager.cpp [hunk 16]
```diff
@@ -506,320 +502,252 @@ void FileCacheManager::PrefetchS3Objs(std::vector<std::string> prefetchObjs) {
...
+        addReadRequests->emplace_back(splitRequest);
+        deletingReq->emplace_back(request.chunkPos);
+        readOffset += splitRequest.len;
+        /*
+             -----                 read block           -
+                ------             S3ChunkInfo
+        */
+        if (fileOffset + length <= s3ChunkInfoOffset + s3ChunkInfoLen) {
+            if (s3ChunkInfo.zero()) {
+                VLOG(9) << "111";
```
Comment (ilixiaocui) [inline curvefs/src/client/s3/client_s3_cache_manager.cpp:561]: ？

File: curvefs/src/client/s3/client_s3_cache_manager.cpp (hunk 9 above)
Comment (wu-hanqing) [reply curvefs/src/client/s3/client_s3_cache_manager.cpp:1095]: because no one handles this return value. but, now, I think you should rename this function to WriteNewDataCache, because you just create a new data cache and copy write data to it.

File: curvefs/src/client/s3/client_s3_cache_manager.cpp (hunk 10 above)
Comment (wu-hanqing) [reply curvefs/src/client/s3/client_s3_cache_manager.cpp:1286]: if I understand correctly, `ChunkCacheManager::FindWriteableDataCache` returns the first datacache in ChunkCacheManager that overlaps with current write operation and removes all following overlap datachche from ChunkCacheManager.

so, why not remove the first overlap data cache together and put it back after finishing the write operation. In this way, data cache doesn't have to care about start offset is changed, and  hold ChunkCacheManager's lock to handle this case.

File: curvefs/src/client/s3/client_s3_cache_manager.cpp (hunk 15 above)
[the remark this answers is not in the document]
Comment (wu-hanqing) [reply curvefs/src/client/s3/client_s3_cache_manager.cpp:759]: Doesn't seem to have changed

**Comment by baijiaruo** [comment]
recheck

**Comment by aspirer** [comment]
recheck

**Review by wu-hanqing — APPROVED** [review]

**Review by ilixiaocui — APPROVED** [review]

**Comment by baijiaruo** [comment]
recheck
